all:
	$(MAKE) -C main-client
	$(MAKE) -C server
	$(MAKE) -C user-for-server


clean: 
	$(MAKE) -C main-client       clean
	$(MAKE) -C server            clean
	$(MAKE) -C user-for-server   clean

.PHONY: main-client server user-for-server

